apiVersion: skaffold/v4beta12
kind: Config
manifests:
  rawYaml:
    - ./infra/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: name/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: 'app/src'
# # Highly recommended for local development of web applications
# # This will forward traffic from your local machine to your running service in Kubernetes
# portForward:
#   - resourceType: Service
#     resourceName: auth-clusterip-srv # The name of your authentication service
#     namespace: default # Assuming your service is in the 'default' namespace
#     port: 3000 # The port your service is listening on inside the cluster
#     localPort: 3000 # The local port you want to access your app from (e.g., http://localhost:3000)
